gems:
- jekyll-gallery-generator
- jekyll-redirect-from

url: http://fallingwater-jekyll-theme.github.io
# baseurl: "/"
# url: http://localhost:3000

name: Fallingwater Jekyll Theme
brand: Fallingwater Jekyll Theme
description: A Jekyll theme for any creative portfolio-driven person/business.
keyword: jekyll, theme, portfolio, creative

email: todo@you.com
phone: +61 0000 0000
# Keep address to one line if you want to use maps (for URL ecaping)
address: 1 Infinite Loop, Cupertino, CA

author: Nathan Birrell

analytics: UA-81747047-1
year: 2016
markdown: kramdown
exclude:
  - node_modules

permalink: pretty

gallery:
  dir: project-photos       # Path to the gallery
  title: "Project Photos"   # Title for gallery index page
  sort_field: "title"       # How to sort galleries on the index page.
  scale_method: fill
  thumbnail_size:
    x: 1080                 # max width of thumbnails (in pixels)
    y: 600                  # max height of thumbnails (in pixels)

latest_project_url: '/projects'
